// Direct Vue adaptation of ReactBits' ColorBends WebGL implementation.
import * as THREE from 'three';

const MAX_COLORS = 8;
const vertexShader = `varying vec2 vUv; void main(){ vUv=uv; gl_Position=vec4(position,1.0); }`;
const fragmentShader = `
#define MAX_COLORS ${MAX_COLORS}
uniform vec2 uCanvas;uniform float uTime;uniform float uSpeed;uniform vec2 uRot;uniform int uColorCount;uniform vec3 uColors[MAX_COLORS];uniform int uTransparent;uniform float uScale;uniform float uFrequency;uniform float uWarpStrength;uniform vec2 uPointer;uniform float uMouseInfluence;uniform float uParallax;uniform float uNoise;uniform int uIterations;uniform float uIntensity;uniform float uBandWidth;varying vec2 vUv;
void main(){float t=uTime*uSpeed;vec2 p=vUv*2.0-1.0;p+=uPointer*uParallax*0.1;vec2 rp=vec2(p.x*uRot.x-p.y*uRot.y,p.x*uRot.y+p.y*uRot.x);vec2 q=vec2(rp.x*(uCanvas.x/uCanvas.y),rp.y);q/=max(uScale,0.0001);q/=0.5+0.2*dot(q,q);q+=0.2*cos(t)-7.56;q+=(uPointer-rp)*uMouseInfluence*0.2;for(int j=0;j<5;j++){if(j>=uIterations-1)break;vec2 rr=sin(1.5*(q.yx*uFrequency)+2.0*cos(q*uFrequency));q+=(rr-q)*0.15;}vec3 sumCol=vec3(0.0);float cover=0.0;vec2 s=q;for(int i=0;i<MAX_COLORS;i++){if(i>=uColorCount)break;s-=0.01;vec2 r=sin(1.5*(s.yx*uFrequency)+2.0*cos(s*uFrequency));float m0=length(r+sin(5.0*r.y*uFrequency-3.0*t+float(i))/4.0);float kBelow=clamp(uWarpStrength,0.0,1.0);float kMix=pow(kBelow,0.3);float gain=1.0+max(uWarpStrength-1.0,0.0);vec2 warped=s+(r-s)*kBelow*gain;float m1=length(warped+sin(5.0*warped.y*uFrequency-3.0*t+float(i))/4.0);float m=mix(m0,m1,kMix);float w=1.0-exp(-uBandWidth/exp(uBandWidth*m));sumCol+=uColors[i]*w;cover=max(cover,w);}vec3 col=clamp(sumCol,0.0,1.0)*uIntensity;if(uNoise>0.0001){float n=fract(sin(dot(gl_FragCoord.xy+vec2(uTime),vec2(12.9898,78.233)))*43758.5453123);col=clamp(col+(n-0.5)*uNoise,0.0,1.0);}float a=uTransparent>0?cover:1.0;gl_FragColor=vec4(uTransparent>0?col*a:col,a);}`;
const toColor = hex => { const value=hex.replace('#','').trim(); const parts=value.length===3?value.split('').map(c=>c+c):[value.slice(0,2),value.slice(2,4),value.slice(4,6)]; return new THREE.Vector3(...parts.map(part=>parseInt(part,16)/255)); };
export function mountColorBends(container, options={}) {
  const setting={rotation:90,speed:.2,colors:['#fff','#cbeaff','#5eaefa','#075bb2'],transparent:false,autoRotate:0,scale:1,frequency:1,warpStrength:1,mouseInfluence:1,parallax:.5,noise:.015,iterations:1,intensity:1.25,bandWidth:6,...options};
  const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-1,1,1,-1,0,1),geometry=new THREE.PlaneGeometry(2,2),colors=Array.from({length:MAX_COLORS},()=>new THREE.Vector3()); setting.colors.slice(0,MAX_COLORS).map(toColor).forEach((color,index)=>colors[index].copy(color));
  const material=new THREE.ShaderMaterial({vertexShader,fragmentShader,uniforms:{uCanvas:{value:new THREE.Vector2(1,1)},uTime:{value:0},uSpeed:{value:setting.speed},uRot:{value:new THREE.Vector2(1,0)},uColorCount:{value:Math.min(setting.colors.length,MAX_COLORS)},uColors:{value:colors},uTransparent:{value:setting.transparent?1:0},uScale:{value:setting.scale},uFrequency:{value:setting.frequency},uWarpStrength:{value:setting.warpStrength},uPointer:{value:new THREE.Vector2()},uMouseInfluence:{value:setting.mouseInfluence},uParallax:{value:setting.parallax},uNoise:{value:setting.noise},uIterations:{value:setting.iterations},uIntensity:{value:setting.intensity},uBandWidth:{value:setting.bandWidth}},premultipliedAlpha:true,transparent:true}); scene.add(new THREE.Mesh(geometry,material));
  const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0,setting.transparent?0:1);renderer.domElement.className='color-bends-canvas';container.appendChild(renderer.domElement);
  const resize=()=>{const width=container.clientWidth||1,height=container.clientHeight||1;renderer.setSize(width,height,false);material.uniforms.uCanvas.value.set(width,height)};const observer=new ResizeObserver(resize);observer.observe(container);resize();const target=new THREE.Vector2(),current=new THREE.Vector2();const move=event=>{const rect=container.getBoundingClientRect();target.set(((event.clientX-rect.left)/(rect.width||1))*2-1,-((event.clientY-rect.top)/(rect.height||1))*2+1)};container.addEventListener('pointermove',move);const clock=new THREE.Clock();let frame;const draw=()=>{const delta=clock.getDelta(),elapsed=clock.elapsedTime,radians=((setting.rotation%360)+setting.autoRotate*elapsed)*Math.PI/180;material.uniforms.uTime.value=elapsed;material.uniforms.uRot.value.set(Math.cos(radians),Math.sin(radians));current.lerp(target,Math.min(1,delta*8));material.uniforms.uPointer.value.copy(current);renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();
  return ()=>{cancelAnimationFrame(frame);observer.disconnect();container.removeEventListener('pointermove',move);geometry.dispose();material.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
}
